# Generated by Django 5.1.6 on 2025-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
