# Generated by Django 5.1.7 on 2025-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default=(), max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=()),
        ),
    ]
