# Generated by Django 5.1.7 on 2025-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_city_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=300),
        ),
    ]
