# Generated by Django 5.1.7 on 2025-04-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orders_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
