# Generated by Django 5.1.7 on 2025-04-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_adress_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
