# Generated by Django 5.1.7 on 2025-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_orders_city_remove_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
