# Generated by Django 5.1.7 on 2025-04-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders_city_orders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
