# Generated by Django 5.1.6 on 2025-04-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default='xxxxxxxxxx'),
        ),
    ]
