# Generated by Django 5.1.6 on 2025-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
