# Generated by Django 5.1.6 on 2025-04-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
