# Generated by Django 5.1.6 on 2025-04-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
