# Generated by Django 5.1.6 on 2025-04-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=3000)),
                ('city', models.CharField(max_length=3000)),
                ('state', models.CharField(max_length=3000)),
                ('zip_code', models.CharField(max_length=3000)),
                ('phone', models.CharField(default='', max_length=111)),
            ],
        ),
    ]
