# Generated by Django 5.1.6 on 2025-04-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_orders_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='phone',
        ),
    ]
