# Generated by Django 5.1.6 on 2025-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
