# Generated by Django 5.1.7 on 2025-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
